[package]
name = "pokemon-battle-cli"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
pokemon-battle-matrix = { path = ".." }
rand = { version = "0.8", features = ["std", "small_rng"] }
